### ISSUE TITLE
Добавить на страницу с вечно пустым календарем вечно пустой букинг.

### ISSUE THREAD

**Issue by Fl0p** [minsk-hackerspace/hsWEB#102]
Код таков: 
```
<iframe src="https://mxc.skedda.com/booking?embedded=true" style="width: 100%; height: 1000px;"></iframe>
```

**Comment by k2m30** [comment]
тормозная какая-то. done.

**Comment by Fl0p** [comment]
Календарь то можно было бы оставить )

**Comment by Fl0p** [comment]
Ивенты всякие регулярные вдруг у нас появятся.

**Comment by Fl0p** [comment]
Да и вот у нас есть.
![screen shot 2016-09-21 at 14 54 34](https://cloud.githubusercontent.com/assets/1046777/18709952/5db76e7c-800b-11e6-8f0c-d8fd5c014d65.png)

**Comment by Fl0p** [comment]
О еще будет интеграция с Г-Календарем
http://support.skedda.com/Bookings/can-i-sync-skedda-with-google-calendar

**Comment by k2m30** [comment]
до реализации #94 календарь я убрал.

**Comment by Fl0p** [comment]
@k2m30 
А я хотел туда ивент создать :(

**Comment by k2m30** [comment]
Так создай через новости на сайте. Будет плашка на главной.

**Comment by QuAzI** [comment]
Новости на сайте уже есть без коммитов и плясок с бубном? RSS? Ещё какие-нибудь ныне не используемые и ни с чем не синкающиеся весёленькие технологии? Верните календарь - он сикается между всеми подписавшимися на него без плясок и бубнов.
