### ISSUE TITLE
Отсутствует ссылка для регистрации в трекере времени железа

### ISSUE THREAD

**Issue by jekhor** [minsk-hackerspace/hsWEB#107]
Сабж, на https://hackerspace.by/calendar. Без регистрации толку никакого.

**Comment by Fl0p** [comment]
Тыкни в любую клеточку и выскочит:
![screen shot 2016-09-29 at 12 00 29](https://cloud.githubusercontent.com/assets/1046777/18947592/6930615a-863c-11e6-9acd-d1bc70c09eb3.png)

**Comment by jekhor** [comment]
У меня не выскакивает

**Comment by k2m30** [comment]
@jekhor http://mxc.skedda.com/ ?

**Comment by Fl0p** [comment]
Да даже на странице 
Тыкаю в клетку:
![screen shot 2016-09-29 at 12 03 51](https://cloud.githubusercontent.com/assets/1046777/18947723/e7bda104-863c-11e6-8ea4-615075402155.png)
Тыкаю на логин:
![screen shot 2016-09-29 at 12 04 07](https://cloud.githubusercontent.com/assets/1046777/18947734/f014a8de-863c-11e6-9a5d-1afee86900b8.png)

Возможно твой браузер как-то блочит жабаскрипт в ифрэйме?

**Comment by k2m30** [comment]
@Fl0p да ладно, добавим сейчас, надо понять, что добавлять.

**Comment by jekhor** [comment]
Оказывается, после регистрации надо ещё сходить в почту, кликнуть по ссылке и только там оно предлагает залогиниться через ФБ. И тогда таки всё видно.

**Comment by Fl0p** [comment]
@jekhor вот лично тебе видно даже без регистрации :)
 Как читателю info@hackerspace.by все брони туда отправляются.

**Comment by jekhor** [comment]
Коммита, закрывающего вопрос. не было.

**Comment by k2m30** [comment]
Да, правильно.

@jekhor Женя, напиши, что добавить.

**Comment by jekhor** [comment]
Ссылку на регистрацию (чёрт, уже забыл, где она была), которую флоп кидал.

**Comment by Fl0p** [comment]
Надо добавить 50$ каждый месяц :)
![screen shot 2016-09-29 at 12 20 52](https://cloud.githubusercontent.com/assets/1046777/18948299/309591b4-863f-11e6-8577-4cee1d151865.png)

**Comment by Fl0p** [comment]
Ссылка эта ?
https://mxc.skedda.com/register?key=595bab5

Но можно и без нее если тыкать прямо в клеточку незалогиненным она там появится.
Не знаю как у вас в браузерах но у меня в хроме рега прямо в iframe возможна.

**Comment by k2m30** [comment]
#108
