### ISSUE TITLE
Подвал со ссылкой на GitHub и рассылку

### ISSUE THREAD

**Issue by abitrolly** [minsk-hackerspace/hsWEB#112]
В продолжение #77. Надо отделять ссылки по приоритетам. Людям, которым нужно исправить ошибку на странице или дизайн, критично быстро добраться до кода. Людей с вопросам критично быстро отправлять в рассылку, поэтому обе ссылки нужно иметь в подвале, неважно откуда бы пользователь не пришёл.

**Comment by yahor** [comment]
@abitrolly Дык якія прапановы па-паляпшэнню? Як раздзяляць?
дадаць спасылку на гітха б? дык можна завітаць у праекты і там знайсці сайт
Ці неабходна дадаць сказ пра праўкі сайта ў фуцеры?

**Comment by abitrolly** [comment]
> дык можна завітаць у праекты і там знайсці сайт

Возможность есть и такой путь нельзя исключать, но совсем всё кисло по переходам. 
https://github.com/minsk-hackerspace/hsWEB/graphs/traffic?referrer=hackerspace.by#top-domains

Надо добавить в подвал ссылку и посмотреть, как статсы изменятся.

**Comment by abitrolly** [comment]
Ещё надо добавить видео, как править сайт, а то есть тут у нас товарищи, которые хотелки закрывают, а как их делать показать не могут.

**Comment by abitrolly** [comment]
> Ці неабходна дадаць сказ пра праўкі сайта ў фуцеры?

Без капитанства. Ссылка - это удобняшка и подсказка для тех, кто в теме. Остальные будут через проект 8 попадать.

**Comment by vicseq** [comment]
А инструкция в обычном тексте есть?

**Comment by abitrolly** [comment]
У гитхаба отличная инструкция, но focus span у людей слишком мал, чтобы её осилить.

**Comment by abitrolly** [comment]
Если бы у меня в детстве был такой инет, как сейчас и бабло на стим, вряд ли бы я так много сейчас знал про то, как конфигурить SSH на винде, и про вообще про всю эту бадягу с ключами.

**Comment by vicseq** [comment]
On Tue, Oct 4, 2016 at 2:22 PM, Anatoli Babenia
<notifications@github.com> wrote:
>
> У гитхаба отличная инструкция, но focus span у людей слишком мал, чтобы её осилить.


Именно поэтому нужна инструкция не для гитхаба, а для этого сайта. И
лучше текст по шагам со ссылками, а не видео.

**Comment by abitrolly** [comment]
Пока надо добавить ссылку в футер, а то фичекрип начинается.

**Comment by k2m30** [comment]
бляя
> Людям, которым нужно исправить ошибку на странице или дизайн, критично быстро добраться до кода

это что за кейс такой? 

если человек что-то правит на сайте он
а) участник ХС
б) знает, кому написать и спросить, благо вариантов много
ц) если у него есть код, у него автоматом есть ссылка на Гитхаб!
д) https://github.com/minsk-hackerspace/hsWEB/wiki

Давайте блин из-за мифических кейсов все запихаем на сайт.

**Comment by k2m30** [comment]
И на странице контактов у нас шесть способов с нами связаться плюс три телефона.

Кому там чего не хватает?

**Comment by Fl0p** [comment]
Не мифический, а извращенный.

Чтобы поправить ошибку на сайте нужно ходить по ссылке в гитхаб,
стягивать код, рассматривать его, разбираться как запустить локально,
разбираться как устроен сам сайт, где там конткнт, а где дизайн, затем править, затем пулреквест, затем деплоить.


Не слишком ли много стэпов?
Тут быстро вообще не получится никак.

Такими извращениями заниматся мало кто желает.

Чтобы было быстро нужна просто ссылка edit 
В таком случае весь контент должен быть либо в базе как в вики
либо в файлах к которым есть доступ как гитхабпэйджс

Тогда все будет просто и без лишних стэпов.

Тогда и контент будет генерится, и ошибки фиксится и наступит полное и безоговорочное счастье.

**Comment by Fl0p** [comment]
@k2m30 звонили ли по этим телефонам хоть раз чтобы исправить ошибку или что-то добавить на сайт?

Вот и ответ о том работает ли способ.

**Comment by k2m30** [comment]
@Fl0p это ответ на вопрос, есть ли такие люди, которым хоть один из таких контактов нужен

**Comment by k2m30** [comment]
> Такими извращениями заниматся мало кто желает.
Это называется "порог входа". И таких людей должно быть мало. Хочешь вносить правки - будь добр стать участником и освоить азы даже не кодинга, а пользования интернетом.

Редактировать wiki страницу много навыков не надо.

**Comment by Fl0p** [comment]
@k2m30 

> есть ли такие люди
Если на номер не звонят это не значит что людей нет.
Это значит люди не верят что можно дозвониться. 

> Это называется "порог входа".

Много ли людей переступило этот ваш порог?

Если уже достаточно - то можно вообще закрыть дверь.
Если не достаточно - то следует этот порог снижать.

**Comment by k2m30** [comment]
@Fl0p ответ на этот вопрос очень простой

https://github.com/minsk-hackerspace/hsWEB/graphs/contributors

плюс те, кто писал issues.

Итого - 10.

Сколько тех, кто искренне хотел, но не смог "преодолеть порог"?
Известных мне - ноль.

Типичный пример Наташи Боричевской @nb8 - ей текст глаза резал, она спросила, как ей быть, получила ответ, создала пачку issues на гитхабе, без строчки кода. 
Все зафиксили.
Аминь.

**Comment by Fl0p** [comment]
@k2m30 
Вопрос был достаточно ли?

**Comment by k2m30** [comment]
> Сколько тех, кто искренне хотел, но не смог "преодолеть порог"?
> Известных мне - ноль.

Да.

**Comment by Fl0p** [comment]
Ну тогда все отлично.
Счастье уже наступило :)

**Comment by yahor** [comment]
закрываем?
