### ISSUE TITLE
Дадаць лакалізацыі на I18n (en, by, ru)

### ISSUE THREAD

**Issue by yahor** [minsk-hackerspace/hsWEB#14]
так як на сайт ёсць спысылка з каталога хакерспэйсаў(http://hackerspaces.org/). 
я вырашыў дадаць 3-х моўе на сайт. 

Хуткім часам зраблю ПР. 

- усе старонкі і тэксты будуць на трох мовах
- апісанне праекта таксама можна будзе дадаваць на 3 мовах
- мова па-змоўчанні застаецца расейская (ці ёсць іншыя меркаванні ў суполкі?)

**Comment by k2m30** [comment]
@yahor Закрываю як wontfix цi што?

**Comment by yahor** [comment]
@k2m30 так. закрываю. да перакладаў рукі не даходзяць.
