### ISSUE TITLE
Расписать workflow попадания в участники ХС

### ISSUE THREAD

**Issue by jekhor** [minsk-hackerspace/hsWEB#22]
Сейчас из сайта не очевидно, как именно стать постоянным участником. В разделе "присоединяйтесь" не написано, как это сделать :)

**Comment by yahor** [comment]
@jekhor  @agutikov  @k2m30  Даўно вісіць. Закрыць ці можа варта зрабіць?

**Comment by k2m30** [comment]
outdated
