### ISSUE TITLE
Убить мой изначальный форк и сделать minsk-hackerspace/hspace основным

### ISSUE THREAD

**Issue by k2m30** [minsk-hackerspace/hsWEB#45]
неудобно pull-request'ы делать

**Comment by abitrolly** [comment]
https://help.github.com/articles/transferring-a-repository/#transferring-from-a-user-to-an-organization

**Comment by abitrolly** [comment]
@k2m30 так в чём проблема? https://help.github.com/articles/transferring-a-repository/#transferring-between-user-accounts

**Comment by abitrolly** [comment]
ping @k2m30 

Может просто создадим новый репозиторий с нуля и запушим туда? @jekhor. @yahor - вы тут самые активные. Что скажете?

**Comment by yahor** [comment]
@abitrolly  як па мне то трэба рабіць трансфер, каб гісторыя пераносілася таксама

**Comment by jekhor** [comment]
Трансфер уже не сделаешь, ибо тут все issues. Миша, так убей свой репозиторий и форкни отсюда, и всё.

**Comment by abitrolly** [comment]
@jekhor мне кажется, что Миша в оффлайне, и уже 9 месяцев как.

**Comment by k2m30** [comment]
ну-ну

**Comment by k2m30** [comment]
Свой форк убил, теперь он наследуется от @hudbrog

**Comment by abitrolly** [comment]
А вот @hudbrog точно в оффлайне. Есть с ним контакт? У меня нет.

**Comment by hudbrog** [comment]
а? че происходит?

**Comment by abitrolly** [comment]
@hudbrog УБЕЙ СВОЙ ФОРК!! УБЕЙ, УБЕЙ ЕГО. ЫЫЫ.. :fork_and_knife:  :B

В общем надо тебе избавиться от своей копии сайта, а то GitHub считает её основной и предлагает pull request'ы слать туда.

**Comment by hudbrog** [comment]
https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/

"To detach the fork and turn it into a standalone repository on GitHub, contact GitHub support."
Идти вот сюда: https://github.com/contact от имени учетки minsk-hackerspace. Обычно обрабатывают в течении пары часов.

**Comment by abitrolly** [comment]
Проще убить, чем просить. =)

https://help.github.com/articles/deleting-a-repository/
https://help.github.com/articles/what-happens-to-forks-when-a-repository-is-deleted-or-changes-visibility

**Comment by abitrolly** [comment]
@k2m30, @hudbrog ништяк. Теперь всё шоколадненько. =)
