### ISSUE TITLE
Новый проект не редактируется

### ISSUE THREAD

**Issue by agutikov** [minsk-hackerspace/hsWEB#53]
http://www.hackerspace.by/projects/12/edit

The page you were looking for doesn't exist.
You may have mistyped the address or the page may have moved.
If you are the application owner check the logs for more information.

**Comment by agutikov** [comment]
@project = Project.published.find(params[:id])

app/controllers/projects_controller.rb:69:in `set_project'

Если поменять на Project.find(params[:id]) - работает

**Comment by agutikov** [comment]
Поле public - это значит все могут редактировать.
А что такое предполагалось в app/models/project.rb
scope :published, -> { where public: true }
?

**Comment by yahor** [comment]
https://github.com/minsk-hackerspace/hsWEB/pull/55

**Comment by yahor** [comment]
@agutikov 
хацеў выкарыстаць для прагляду, каб паказваць толькі апублікаваныя. але паспягаўся і не туды ўставіў. Падумаю яшчэ над гэтым
  def show
    @project = Project.find(params[:id])
  end

**Comment by jekhor** [comment]
On Thu, Jul 23, 2015 at 12:30:38AM -0700, Yahor wrote:
> @agutikov 
> хацеў выкарыстаць для прагляду, каб паказваць толькі апублікаваныя. але паспягаўся і не туды ўставіў. Падумаю яшчэ над гэтым
>   def show
>     @project = Project.find(params[:id])
>   end

publc – гэта не "апублікаваныя", а "грамадскія".

> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/minsk-hackerspace/hsWEB/issues/53#issuecomment-124005046

-- 
Yauhen Kharuzhy
			skype: jekhor

**Comment by abitrolly** [comment]
А можно редактировать через Github?

**Comment by yahor** [comment]
так. можна мяняць файлы. 
Праблема яшчэ актуальна, ці можна закрываць?
