### ISSUE TITLE
Новости и проекты

### ISSUE THREAD

**Issue by agutikov** [minsk-hackerspace/hsWEB#62]
1) Попытка удалить новость http://hackerspace.by/news/5
привела к удалению проекта http://hackerspace.by/projects/5
(вроде это был "hackable webspace")
Необходимо пофиксить кнопку удаления и восстановить проект

2) "Назад к списку новостей" - ведёт к списку проектов

3) Новость http://hackerspace.by/news/4 создалась, но не редактируется и не просматривается

**Comment by yahor** [comment]
эх. вось для гэтага і трэба тэсты і код рэвью. зараз выправім. 
пытанне што за праект быў пад ІД 5?
ёсць дамп ці данныя?
@agutikov  @jekhor

**Comment by yahor** [comment]
https://github.com/minsk-hackerspace/hsWEB/pull/64/files

**Comment by jekhor** [comment]
On Tue, Sep 22, 2015 at 12:45:31PM -0700, Yahor wrote:
> эх. вось для гэтага і трэба тэсты і код рэвью. зараз выправім. 
> пытанне што за праект быў пад ІД 5?
> ёсць дамп ці данныя?
> @agutikov  @jekhor 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/minsk-hackerspace/hsWEB/issues/62#issuecomment-142398214

https://web.archive.org/web/20141108164245/http://hackerspace.by/projects/5




-- 
Yauhen Kharuzhy
			skype: jekhor

**Comment by yahor** [comment]
@agutikov  ня маю доступ каб дадаць па новай выдалены праект. трэба каб дадаў нехта іншы

**Comment by agutikov** [comment]
@k2m30 Михаил, надо дать людям доступ к сайту :)

**Comment by k2m30** [comment]
done

**Comment by yahor** [comment]
http://hackerspace.by/projects/16 дадаў вось так

**Comment by yahor** [comment]
@agutikov  можна закрываць?

**Comment by agutikov** [comment]
Пункци 1 и 2 пофикшены. Новость удалилась и кнопка "назад" ведёт куда надо.

А третий нет. 
Новость http://hackerspace.by/news/4 создалась, но не редактируется и не просматривается
Может это не баг а фича? Неопределённая вечеринка же?

**Comment by agutikov** [comment]
3 moved to https://github.com/minsk-hackerspace/hsWEB/issues/67
