### ISSUE TITLE
Функционал: вешать афиши на главную

### ISSUE THREAD

**Issue by nb8** [minsk-hackerspace/hsWEB#63]
Задача: чтобы авторизованные пользователи могли удобно, без залезания в код, вешать на главную страницу афишу ближайшего мероприятия.
Афиша кликабельна.
То есть пользователь называет событие, загружает картинку, ставит дату, до которой должно висеть и указывает ссылку, куда отправлять по клику.

В идеале еще в новости автоматический репост события.
![default](https://cloud.githubusercontent.com/assets/9879630/10026218/25d86e6e-6169-11e5-9302-31d2209b4bb6.JPG)

**Comment by yahor** [comment]
@nb8 фактычна гэта ёсць навіна з фкнуцыяй размяшчэнне на галоўнай. і вялікім малюнкам. 
А што калі іх некалькі, тады як будзе адбывацца вывад на старонку?

**Comment by nb8** [comment]
Можно вешать только одну, самую ближайшую по дате.

**Comment by yahor** [comment]
https://github.com/minsk-hackerspace/hsWEB/pull/66
