### ISSUE TITLE
Корректура текста на главной

### ISSUE THREAD

**Issue by nb8** [minsk-hackerspace/hsWEB#68]
1) Под заголовком "Как к нам присоединиться? Сколько это стоит?", во последнем абзаце:

Вы так же можете помочь проекту 

исправить на: 
Вы также можете помочь проекту

2) В разделе "Что у нас есть? Всякое":

скоро будет ЧПУ фрезер

исправить на: 
ЧПУ фрезер

**Comment by yahor** [comment]
https://github.com/minsk-hackerspace/hsWEB/pull/69
