### ISSUE TITLE
Функционал: аттачи для скачивания

### ISSUE THREAD

**Issue by nb8** [minsk-hackerspace/hsWEB#74]
В Проекты добавить поле для добавления файла на сайт / создания дополнительной внешней ссылки для скачивания

**Comment by k2m30** [comment]
Внешняя ссылка создается же, у нас все проекты с ними - [вот](http://hackerspace.by/projects/6)

Вот как это делать в [markdown](https://guides.github.com/features/mastering-markdown/)
