### ISSUE TITLE
Добавить в "Устройства" штуки Умного дома 

### ISSUE THREAD

**Issue by nb8** [minsk-hackerspace/hsWEB#75]
Как минимум показания датчика движения. Может, еще что, что с Сергеем захотите 
Сергей Джейгало, автор Умного Дома
https://www.facebook.com/sergejey?fref=ts

**Comment by sergejey** [comment]
Если через API как-то можно добалять устройства и их показания, то я смогу их публиковать сам из системы Умного Дома.
