### ISSUE TITLE
Ссылка на GitHub и рассылку должна светиться на основной

### ISSUE THREAD

**Issue by abitrolly** [minsk-hackerspace/hsWEB#77]

**Comment by agutikov** [comment]
Поддерживаю

**Comment by abitrolly** [comment]
Где править?

**Comment by yahor** [comment]
дадаў пакуль так:

Чем мы здесь занимаемся? Мы творим.
Мы паяем, программируем, вырезаем из металла, пластика и дерева. Мы делаем роботов, дронов и строим станки ЧПУ. Мы собираем 3D-принтеры. Мы делаем печатные платы. Мы делимся опытом и совершаем ошибки. Придумываем новые проекты и улучшаем старые. GitHub: https://github.com/minsk-hackerspace

https://github.com/minsk-hackerspace/hsWEB/pull/83

**Comment by abitrolly** [comment]
Кхм.. Это текст на кому-нибудь ещё тестился? Мне вот не нравится.

**Comment by abitrolly** [comment]
Я имел в виду, что у нас должен быть подвал с иконками, а не куча текста.
