### ISSUE TITLE
Добавить описание Device API

### ISSUE THREAD

**Issue by agutikov** [minsk-hackerspace/hsWEB#78]
Добавить описание Device API
в Wiki   https://github.com/minsk-hackerspace/hsWEB/wiki
или в маркдауне в коде.

Нужно для:  'Добавить в "Устройства" штуки Умного дома' #75 

Конкретно вот эти пункты:
- Создание / регистрация нового устройства
- Создание / регистрация нового события

**Comment by agutikov** [comment]
Походу event_type не надо регистрировать? Устройство может посылать на сайт хоть каждый раз разные event_type?

**Comment by jekhor** [comment]
On Thu, Dec 17, 2015 at 01:18:14AM -0800, Alex Gutikov wrote:
> Походу event_type не надо регистрировать? Устройство может посылать на сайт хоть каждый раз разные event_type?

Да, event type специфичен для устройства, просто текст.


> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/minsk-hackerspace/hsWEB/issues/78#issuecomment-165391274

-- 
Yauhen Kharuzhy

**Comment by k2m30** [comment]
https://github.com/minsk-hackerspace/hsWEB/wiki
