### ISSUE TITLE
Add metadata

### ISSUE THREAD

**Issue by vicseq** [minsk-hackerspace/hsWEB#80]
Дадаць мета тэгі да старонак сайта аналагічна, як рэкамендуецца ў https://groups.google.com/d/msg/hackerspace-minsk/cSH6qR7j_O0/6D2nqIV9CQAJ і https://groups.google.com/d/msg/hackerspace-minsk/cSH6qR7j_O0/PPgwcsF9CQAJ .

**Comment by yahor** [comment]
https://github.com/minsk-hackerspace/hsWEB/pull/81
