### ISSUE TITLE
Добавить на главную маршрут к ХС

### ISSUE THREAD

**Issue by nb8** [minsk-hackerspace/hsWEB#84]
эту штуку
http://www.mapillary.com/map/im/98iGzWktd9tuLs-agQWy2w/photo
прикрутить вместо карты в последний абзац

**Comment by jekhor** [comment]
У меня этот Mapillary тормозит жесточайше в Firefox. Может, сделать таки и ссылку на страницу контактов, где есть просто карта + фото входа?

**Comment by yahor** [comment]
можа ёсць мінімальня версія, без загрузкі іх сайта. Плюс, так, ФФ апошнім часам не любіць джаваскрыпт

**Comment by jekhor** [comment]
Саммоним @Komzpa

**Comment by Komzpa** [comment]
@jekhor, как у тебя видятся вот такие? они, похоже, до первого клика грузят только превью фотки и не пытаются делать панорамы.
http://bl.ocks.org/knikel/010115b08ebe30baba86
http://bl.ocks.org/knikel/151a77df042cd3890502

**Comment by jekhor** [comment]
Пока не наведёшь мышку — размытое фото, наведёшь — резкое. Кликаешь по иконке в центре — превращается в тормозючку.

**Comment by Komzpa** [comment]
Отлично, работает именно так, как ожидалось - страницу не тормозит, пока не
обяжут :)
В общем, прямо там же пример использования, айдишники можно вытащить из
ссылок.

вт, 16 февр. 2016 г. в 16:57, jekhor <notifications@github.com>:

**Comment by jekhor** [comment]
On Tue, Feb 16, 2016 at 06:42:33AM -0800, Darafei Praliaskouski wrote:
> Отлично, работает именно так, как ожидалось - страницу не тормозит, пока не
> обяжут :)
> В общем, прямо там же пример использования, айдишники можно вытащить из
> ссылок.

Так а зачем они такие тормозючие скрипты написали, почему у того же
гугла-яндекса не тормозят? Или там флеш?

> 
> вт, 16 февр. 2016 г. в 16:57, jekhor <notifications@github.com>:
> 
> > Пока не наведёшь мышку — размытое фото, наведёшь — резкое. Кликаешь по
> > иконке в центре — превращается в тормозючку.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/minsk-hackerspace/hsWEB/issues/84#issuecomment-184692636>
> > .
> >
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/minsk-hackerspace/hsWEB/issues/84#issuecomment-184706196

-- 
Yauhen Kharuzhy

**Comment by Komzpa** [comment]
@jekhor там не флеш, там трёхмерное пространство с моделями, на которые натянута gl-текстурка. у гугла-яндекса - просто панорамы с сферической проекцией. :)
на моём компе в хроме оно не тормозит. как обычно, предлагаю быть на острие и допиливать браузеры, если с ними беда :3

**Comment by jekhor** [comment]
WebGL? Когда-то оно у меня шевелилось на моём ноуте, а потом кто-то всё сломал, и шевелиться перестало.

**Comment by yahor** [comment]
у хроме ў мяне працу ўсё добра. Дык якая рэзалюцыя будзе?

**Comment by nb8** [comment]
> у хроме ў мяне працу ўсё добра. Дык якая рэзалюцыя будзе?
У меня тоже все отлично. Давай оставим обе ссылки: первая --- эта, как есть (пока не хакнули), названная "маршрут", и та, что была раньше, названная "карта". 

Мы находимся по адресу: ул. Беды, 45 (карта и маршрут).

**Comment by Komzpa** [comment]
Вопрос же изначально был не про ссылку - эту карту можно впихнуть вместо той пары фотки и карты, что есть сейчас на http://hackerspace.by/contacts. В том формате оно так же и выглядит (карта+фотка), и до клика функционально не отличается от текущего решения.

**Comment by nb8** [comment]
Идёт.

17 февраля 2016 г., 14:55 пользователь Darafei Praliaskouski <
notifications@github.com> написал:

**Comment by abitrolly** [comment]
http://bl.ocks.org/knikel/010115b08ebe30baba86
серый квадрат - наверное что-то из вебгля требует.
