### ISSUE TITLE
На главной: присутствующие в ХС

### ISSUE THREAD

**Issue by nb8** [minsk-hackerspace/hsWEB#85]
Когда в ХС есть только кто-то, не записанный в базе, на главной отображается такое:

Hello World!
Это сайт Минского хакерспейса. Сейчас у нас открыто. Приходите.
Сейчас в хакерспейсе:
-------------------------------------
Нужно при отсутствии авторизованных пользователей оставить просто:

Hello World!
Это сайт Минского хакерспейса. Сейчас у нас открыто. Приходите.

**Comment by abitrolly** [comment]
Сейчас в хакерспейсе: N-анонимных сусликов.

**Comment by nb8** [comment]
А, да, трибьют ту гуглдокс) Можно на n неизвестных сделать рендомные ники. HAL9000, Мужик с Паяльником, Р. Дэниел Оливо, Вепрь Ы, Невыспавшийся Гик...
