### ISSUE TITLE
График присутствия в ХС

### ISSUE THREAD

**Issue by agutikov** [minsk-hackerspace/hsWEB#86]
Вопрос: есть ли смысл и надо ли добавлять на сайт вот такой график посещаемости ХС-а:
http://agutikov.github.io/d3js-heatmap/

В принципе из данных можно будет рисовать что угодно. Например вероятность обнаружить хс открытым в зависимости от дня недели и времени - будет 7 прикольных графиков.  Поэтому по-хорошему надо выделить страничку куда можно будет добавлять ссылки на графики, и каталог куда класть скрипты и статические html / haml  странички - заготовки для графиков. В принципе можно обойтись одной и разруливать всё на жаваскрипте, но мне так не очень нравится.

Попутно: 
events/ - требует логин
а devices/1.json - не требует
Так и должно быть?

**Comment by abitrolly** [comment]
2016-03-10 18:27 GMT+03:00 Alex Gutikov <notifications@github.com>:

> Вопрос: есть ли смысл и надо ли добавлять на сайт вот такой график
> посещаемости ХС-а:
> http://agutikov.github.io/d3js-heatmap/
>
> В принципе из данных можно будет рисовать что угодно.
>
Данные на сайт добавлять нужно, а график вторичен. =)

> Например вероятность обнаружить хс открытым в зависимости от дня недели и
> времени - будет 7 прикольных графиков.
>
Вероятность - это уже API. На чём реализовывать будешь?

> Поэтому по-хорошему надо выделить страничку куда можно будет добавлять
> ссылки на графики, и каталог куда класть скрипты и статические html / haml
> странички - заготовки для графиков. В принципе можно обойтись одной и
> разруливать всё на жаваскрипте, но мне так не очень нравится.
>
Не страничку надо выделять, а впилить в движок кому-нибудь, кто в теме,
нормальную поддержку статических страниц (с картой сайта и линк-чекером).

  * [ ] карта сайта
  * [ ] статические страницы
  * [ ] линк-чекер

Попутно:
> events/ - требует логин
> а devices/1.json - не требует
> Так и должно быть?
>
ХЗ. Надо смотреть. Насколько я понимаю авторизация нужна только для записи.

**Comment by k2m30** [comment]
#94 - Либо так, либо так.
