### ISSUE TITLE
Скринкаст на хакабл вебсайт

### ISSUE THREAD

**Issue by abitrolly** [minsk-hackerspace/hsWEB#88]
Я обязуюсь записать видос, как хакать сайт хакерспейса. Тупой сценарий:

1. Точки входа - подвал ХС, разметка, страница проекта "Hackable website"
2. GitHub сайта - вход с разметки, GitHib ХСа - вход из подвала, страница проекта - вход на видос
3. Логин, подписка на все события
4. Получение кода, запуск, модификация
5. PR, ревью, запуск в продакшн
6. Метрика - время на цикл

**Comment by k2m30** [comment]
закрываю как невыполненное соцобязательство
