### ISSUE TITLE
Дадаць тэсты на rspec

### ISSUE THREAD

**Issue by yahor** [minsk-hackerspace/hsWEB#9]

**Comment by yahor** [comment]
https://github.com/minsk-hackerspace/hsWEB/pull/79

**Comment by abitrolly** [comment]
Как тестить? И что теститься-то?

**Comment by yahor** [comment]
глядзі пулл рэквест https://github.com/minsk-hackerspace/hsWEB/pull/79/files
як мінімум пішаш кантроллер, мадель, хелпер, напішы тэст.

**Comment by abitrolly** [comment]
И что этот тест делает?
```
+  describe "GET 'show'" do
 +    it "" do
 +      # get :show, id: news.id
 +      # expect(response).to be_success
 +    end
 +  end
```

**Comment by abitrolly** [comment]
И как тестить?

**Comment by abitrolly** [comment]
По этим страницам не лучше ли тест на битые ссылки прикрутить?

**Comment by yahor** [comment]
тэст чакае пакуль я яго дапішу. 
А тэсціраваць вось так http://railscasts.com/episodes/275-how-i-test 

тэст на бітыя спасылкі гэта не функцыянальныя тэсты. можна і то, і то.

**Comment by abitrolly** [comment]
Крутая дока, а команду какую запустить-то? =) Хочу Travis CI добавить.

**Comment by yahor** [comment]
rspec spec/
