### ISSUE TITLE
Можно отредактировать эту страницу

### ISSUE THREAD

**Issue by abitrolly** [minsk-hackerspace/hsWEB#91]
Дать возможность любому человеку редактировать контент, стили и т.п.

1. Сделать рендер статического markdown/html на сайте
2. Вынести ссылку "Можно отредактировать эту страницу" в подвал
3. Проверить совместимость на мобилках
4. Записать видос с помощью recordscreen.py

**Comment by k2m30** [comment]
контент чего?
проектов - реализовано. сайт - никогда.

**Comment by abitrolly** [comment]
> сайт - никогда.

Экспертизы не хватает? =) Давай аргументируй, а то я сейчас тут сам себе аргументов насочиняю.

**Comment by k2m30** [comment]
Я не хочу давать непонятно кому доступ к контенту сайта. 
Есть экспертиза - делай pull-request, посмотрим, разберемся.

**Comment by abitrolly** [comment]
Расслабься. Кому надо - тот сам возьмёт. =)

На самом деле я тоже не собираюсь из этого анонимную вики делать - для этого пиратпад есть. Смысл в том, чтобы удобно херачить реквесты по ссылке со страницы сайта, и соответственно хранить статику на GitHub.
